{
 "title": "PX-CSI Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "FlashArray", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FlashArray Volume Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "px_csi_fafb_apis_volumes_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FlashArray API Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(px_csi_fafb_all_apis_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "By Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CSI Volume Attachments per node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "px_csi_attachments_per_node{node=\"dev-site1-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CSI Volume Attachments per node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "px_csi_attachments_per_node{node=\"dev-site1-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CSI Volume Attachments per node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "px_csi_attachments_per_node{node=\"dev-site1-3\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}